#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM microsoft/dotnet:2.2-sdk AS build-env 
WORKDIR /app

# copy csproj and restore as distinct layers 
RUN ls -sfal
COPY *.csproj ./

RUN dotnet restore

# copy everything else and build 
COPY . ./
RUN dotnet publish -c Release -o out

# build runtime image 
FROM microsoft/dotnet:2.2-aspnetcore-runtime
WORKDIR /app
COPY --from=build-env /app/out .

ENV ASPNETCORE_URLS=http://+:81
EXPOSE 81
EXPOSE 443

ENTRYPOINT ["dotnet", "GreybeanSolutionsCompanySite.dll"]
